services:
  mongodb:
    image: mongo:latest
    container_name: logibot_mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD_ROOT}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
