services:
  app:
    container_name: logibots_backend

    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    networks:
      - logibots

networks:
  logibots:
    driver: bridge
    name: logibots
