# secrets.yaml - Vers√£o com valores codificados em Base64
apiVersion: v1
kind: Secret
metadata:
  name: logibot-secrets
type: Opaque
data:
  API_KEY: QU1PTUlOSEFFU1BPU0F0WnQ4d3VWVioyQGQ3XmJpMTk1bE83XmE4QGw2JCQhRCRoNHRTVThldHYmN2MmaXYzaTkkazY2MWQlcFViYXRhdGE=
  DB_NAME: Q2hhdFNBRUw=
  FRONT_URL: aHR0cHMvL3NhZWxsb2dpYm90LmNvbQ==
  GOOGLE_CLIENT_ID: OTYwMjMyNDU1ODMxLWZhbGtqZWJodnEybDFzc2V1bWVwYjlkOTJrb2lvczRhLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLUMxNmpqWmwlTTNVaWFnSWtpOGJEdktrczhFRFI=
  GOOGLE_LOGIN_CALLBACK_URL: aHR0cHM6Ly9zYWVsbG9naWJvdC5jb20vYXBpL2F1dGgvZ29vZ2xlL2xvZ2luLWNhbGxiYWNr
  GOOGLE_LOGIN_REDIRECT: aHR0cHM6Ly9zYWVsbG9naWJvdC5jb20vY2hhdA==
  JWT_SECRET: YTFhMmMzZDRlNWY2Nzg5MGdIaUprTG1Ob1BxUnNUdVZ3WHlaMTIzNDU2Nzg5MEFiQ2RFZkdoSWpLbE1uT3BRclM=
  Key_A1: Z1dFTUVLc2VPV3BfZ05zNGs4WDRWRG1SdHh5ZXRPc2g=
  Key_A10: U0k3NHkzM3VjNHZJbjgwNElqSEJBRjhSeEo2YkIzZ3g=
  Key_A11: clhkbWE2em9hYmhPYzdZdXJQTENpM1R1M2NILW5VRDg=
  Key_A12: VkdSa1lQNTlXSDdNMl81Zk1jejlEd25kSFRyOFAtMDY=
  Key_A2: cENHWFozSGlrRnNSYjhLS0RBb3d5ay1TLXFhZmwtT2g=
  Key_A3: SjVsdzBHUGVvTHVuNkp1NWg3UUVsMTlVLTYvRUFrNEE=
  Key_A4: OW1YMzNpS0c3M0NURTNZczh0Q0dnVWdDSThaY0NVU0w=
  Key_A5: Y1l0WFliZ1JKVFRkZzBJcHdXWno0bWVnM2kycmY0c3c=
  Key_A6: RmVudHd3Z3pSOWZTR2FOcnZNcVM4ZXpWSC1CejBLdzk=
  Key_A7: bHZGUmN0ZGIzbXk2MDM1RUpVWDVxcTd0Z3o4UzFFQjY=
  Key_A8: UnkwRGxGQkVRbXgweHRkOFpiRjA1UGFNS3dtMExkSlQ=
  Key_A9: U2Ryd0o3eGtjZDd1UU5CZXdpdDdLbGtKQXlQNHdLVGo=
  MONGO_URI: bW9uZ29kYitzcnY6Ly9yYW1vbmNvYmFyYm9zYTpIU1RVaERoZVM5MmQxTkBAY2x1c3RlcjAucTBiZjgubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
  OLLAMA_API_URL_1: aHR0cHM6Ly9peW82YzVkaWJuMjM0aG8zb25qNGdlYWUuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_10: aHR0cHM6Ly9pcHNhb3JwdW53c2ptdmxzcHRrbGM1a2cuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_11: aHR0cHM6Ly9ncmVramI0b2pwZWY1aDdwYzJ1MnBleWQuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_12: aHR0cHM6Ly9pazJ3cmlxeWxrciZjciRtNXN6azR5dWguYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_2: aHR0cHM6Ly9wdnp6emphdDQyM29hNXR5MnVjejRydGIuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_3: aHR0cHM6Ly9oeTJ4ZGw2Mmo1eTZhZnRkN3Rnb2Q0Y3UuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_4: aHR0cHM6Ly9mdW5iZW1pbXBwMm53cmwzYXN0NDVpcmYuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_5: aHR0cHM6Ly92aW5ma2V5M2MzY29jcTVwNmo2MnF5ZmIuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_6: aHR0cHM6Ly9sbGYzcHJrNzNyN3RsNmZuaje0dGl5cm8uYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_7: aHR0cHM6Ly9zeWVzaGZyeDNlcWV6Zno1aW1raXFsZWcuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_API_URL_8: aHR0cHM6Ly9mZWdweGhoZWhlbGprcXNxdzZwbWY3aGxjLmFnZW50cy5kby1haS5ydW4vYXBpL3YxL2NoYXQvY29tcGxldGlvbnM=
  OLLAMA_API_URL_9: aHR0cHM6Ly94cTZ6MmtobnZwNmtkamJ0bzQ1bnZ6bGQuYWdlbnRzLmRvLWFpLnJ1bi9hcGkvdjEvY2hhdC9jb21wbGV0aW9ucw==
  OLLAMA_COOKIE: X19jZl9ibT1OME10Uzc3S2ZUcENTTWpURVBCM3NxTWJRU3RWZ29wVzF2enlGT20zS3YwLTE3NTQ2ODI4NjMtMS4wLjEuMS16TEgxY1NLUmdfUXpPVlZlNjZyRV93SVNSb0N3UkV3aElBeDljQVZzZ2dZSGduNlp1VmgYamZzSi5pV1YwbmNMTFowQmI3dnNhZ0FQYTRTeXhJNHp5UjU1SDdiOFA5M3FBVV9KMHzuNFp6Yw==
  RASA: aHR0cDovL3Jhc2Etc2VydmVyOjUwMDUvd2ViaG9va3MvcmVzdC93ZWJob29r
  RASA_ACTION: aHR0cDovL3Jhc2EtYWN0aW9uOjUwNTUvd2ViaG9vaw==
  RASA_API: aHR0cDovL3Jhc2Etc2VydmVyOjUwMDUvYXBp
  RECAPTCHA_SECRET_KEY: NkxkREdHY3JBQUFBQUI4SDhpX3BLZi1VTzhKZ1pHaWdHRVNhQlNRYg==
  SMTP_DOMAIN: Z21haWwuY29t
  SMTP_EMAIL: Y2g0N2IwN3NhM2xAZ21haWwuY29t
  SMTP_PASSWORD: enJwanZweXdvbHdlamd6bQ==
  SMTP_PORT: NTg3
