name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          REPO_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_LOWERCASE:latest .
          docker push ghcr.io/$REPO_LOWERCASE:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    environment: production

    steps:
      - name: Deploy to Hetzner VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ../logibot/LogiBot_Backend

            REPO_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/$REPO_LOWERCASE:latest

            git pull origin main

            export API_KEY="${{ secrets.API_KEY }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export FRONT_URL="${{ secrets.FRONT_URL }}"
            export GHCR_PAT="${{ secrets.GHCR_PAT }}"
            export GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
            export GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
            export GOOGLE_LOGIN_CALLBACK_URL="${{ secrets.GOOGLE_LOGIN_CALLBACK_URL }}"
            export GOOGLE_LOGIN_REDIRECT="${{ secrets.GOOGLE_LOGIN_REDIRECT }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export MONGO_URI="${{ secrets.MONGO_URI }}"
            export OLLAMA_API_KEY="${{ secrets.OLLAMA_API_KEY }}"
            export OLLAMA_API_URL="${{ secrets.OLLAMA_API_URL }}"
            export OLLAMA_COOKIE="${{ secrets.OLLAMA_COOKIE }}"
            export RASA="${{ secrets.RASA }}"
            export RASA_ACTION="${{ secrets.RASA_ACTION }}"
            export RASA_API="${{ secrets.RASA_API }}"
            export RECAPTCHA_SECRET_KEY="${{ secrets.RECAPTCHA_SECRET_KEY }}"
            export SMTP_DOMAIN="${{ secrets.SMTP_DOMAIN }}"
            export SMTP_EMAIL="${{ secrets.SMTP_EMAIL }}"
            export SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}"
            export SMTP_PORT="${{ secrets.SMTP_PORT }}"
            export SSH_HOST="${{ secrets.SSH_HOST }}"
            export SSH_KEY="${{ secrets.SSH_KEY }}"
            export SSH_USERNAME="${{ secrets.SSH_USERNAME }}"

            docker-compose down
            docker-compose up -d --build
